`define ADD_A_Im 4'h0
`define MOV_A_B  4'h1
`define IN_A     4'h2
`define MOV_A_Im 4'h3
`define MOV_B_A  4'h4
`define ADD_B_Im 4'h5
`define IN_B     4'h6
`define MOV_B_Im 4'h7
`define OUT_B    4'h9
`define OUT_Im   4'hB
`define JNC_Im   4'hE
`define JMP_Im   4'hF
